= About this Documentation

== Tools

This documentation was made with Antora, which is based on NodeJS. Antora keeps track of documentation sourced from multiple repositories and handles different versions of documentation for the same software.

Apart from a few minor changes to the header and footer, the appearance of this site is left up to the Antora default UI.

== How to Build

This documentation can be generated on any platform so long as you have access to the Illumination Repositories.

The first step in building this documentation is to download the documentation repository, which can be found https://github.com/PercentBoat4164/Illumination-Engine-Documentation[here].

Then, the LTS version (or later) of NodeJS must be installed. For MacOS, Node can be easily installed using brew. For Windows, https://nodejs.org/ has an installer. For Linux, using nvm is likely the easiest way to install recent versions of NodeJS.  A walkthrough of that process can be found https://heynode.com/tutorial/install-nodejs-locally-nvm/[here].

Once NodeJS is properly installed to the LTS version, run the following command in the root of the Documentation Repository.

[source]
npm install

This will download all necessary Antora packages.

Once this is done, run the following command (again in the root of the documentation repository).

[source]
npx antora generate --fetch antora-playbook.yml

This will aggregate all available documentation for Illumination, generate this page, and place it in the build directory. Importantly, when this documentation is generated, it pulls all documentation information directly from the Illumination Repositories. This does not reflect any local changes you may have made to any documentation.

== Altering Documentation and Viewing Changes

If you are a maintainer on any Illumination Repository, including this one, it would be helpful to be able to alter documentation locally and see the resulting Antora pages. In order to accomplish this, Development Antora 'playbooks' (configuration files) have been included in the docs directories of all Illumination repositories. These are named 'antora-playbook-dev.yml'.

The 'antora-playbook.yml' file that is included at the base of this documentation repository will pull directly from git repositories to generate documentation. On the other hand, 'docs/antora-playbook-dev.yml' will reflect local changes. It will generate documentation pages only for the current repository. Once these local documentation changes have been merged into the main branch of their respective repositories, the documentation changes will be reflected in this page (generated by antora-playbook.yml).

To see how your development changes to documentation pages will affect the generated Antora site, first switch to the docs directory. Then run:

[source]
npx antora generate antora-playbook-dev.yml

The generated local documentation will be placed in docs/build.